# -*- mode: ruby -*-
# vi: set ft=ruby :

# Start of the configuration section

# General
VM_IMAGE = "generic/centos7"
PROVIDER = "virtualbox"

# Versions
TERRAFORM_VERSION = "0.13.2"
KUBECTL_VERSION = "v1.18.0"
KUBERNETES_VERSION = "v1.18.6-rancher1-1"   # Check https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.4.5/ to see the supported K8s versions by Rancher

# Resources
CPU_CORES_RANCHER_NODES = 2
MEMORY_RANCHER_NODES = 4096
CPU_CORES_K8S_NODES = 2
MEMORY_K8S_NODES = 2048
CPU_CORES_CTL = 1
MEMORY_CTL = 512

# Node Count
K8S_NODES = 1
RANCHER_NODES = 1

# Network Settings
PRIVATE_IP_RANGE_FOR_NODES = "172.20.20"    # Specify only the first 3 octets
CONTROL_NODE_IP = "172.20.20.5"
RANCHER_NODES_BASE_IP = "172.20.20.1"       # Place Rancher nodes inside .10 - .19
K8S_NODES_BASE_IP = "172.20.20.2"           # Place K8s nodes inside .20 - .29

# End of the configuration section

$prepare_basic_settings = <<SCRIPT

# Deploy key
[ -f /home/vagrant/.ssh/id_rsa ] || {
    cp /vagrant/id_rsa /home/vagrant/.ssh/id_rsa
    cp /vagrant/id_rsa.pub /home/vagrant/.ssh/id_rsa.pub
    chmod 0600 /home/vagrant/.ssh/id_rsa
    chmod 0600 /home/vagrant/.ssh/id_rsa.pub
}
# Allow ssh passwordless
grep 'vagrant@rancher-lab' ~/.ssh/authorized_keys &>/dev/null || {
  cat /vagrant/id_rsa.pub >> ~/.ssh/authorized_keys
  chmod 0600 ~/.ssh/authorized_keys
}
# Exclude all nodes from host checking
cat > ~/.ssh/config <<EOF
Host *
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
EOF
chmod -R 600 ~/.ssh/config
# Allow PublicKeyAuthentication
sudo sed -i 's|#PubkeyAuthentication.*|PubkeyAuthentication yes|g' /etc/ssh/sshd_config
sudo sed -i 's|#AuthorizedKeysFile.*|AuthorizedKeysFile	.ssh/authorized_keys|g' /etc/ssh/sshd_config
# Populate /etc/hosts
for x in {10..#{9+RANCHER_NODES}}; do
  grep #{PRIVATE_IP_RANGE_FOR_NODES}.${x} /etc/hosts &>/dev/null || {
      echo #{PRIVATE_IP_RANGE_FOR_NODES}.${x} rancher-node-${x##?} | sudo tee -a /etc/hosts &>/dev/null
  }
done
for x in {20..#{19+K8S_NODES}}; do
  grep #{PRIVATE_IP_RANGE_FOR_NODES}.${x} /etc/hosts &>/dev/null || {
      echo #{PRIVATE_IP_RANGE_FOR_NODES}.${x} k8s-node-${x##?} | sudo tee -a /etc/hosts &>/dev/null
  }
done
# Create Rancher working directory
sudo mkdir -p /opt/rancher-setup
sudo chown vagrant:vagrant /opt/rancher-setup
# Disable swap
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
# Install basic & lab tools
sudo yum install htop vim unzip -y
# Set SELinux to permissive mode
sudo setenforce 0
sudo sed -i --follow-symlinks 's/^SELINUX=.*/SELINUX=permissive/g' /etc/sysconfig/selinux
# Disable Firewallw
sudo systemctl stop firewalld
sudo systemctl disable firewalld

SCRIPT

$terraform_installation = <<SCRIPT

wget https://releases.hashicorp.com/terraform/#{TERRAFORM_VERSION}/terraform_#{TERRAFORM_VERSION}_linux_amd64.zip
unzip terraform_#{TERRAFORM_VERSION}_linux_amd64.zip
chmod +x terraform
mv terraform /usr/local/bin/

SCRIPT

$rke_cluster_yaml_generation = <<SCRIPT

sudo yum check-update
sudo yum install python3-pip git vim -y
sudo -H pip3 install j2cli[yaml]
cd /vagrant
echo "kubernetes_version: "#{KUBERNETES_VERSION} > data.yml
echo "rancher_nodes:" >> data.yml
for x in {10..#{9+RANCHER_NODES}}; do
    echo "  - "#{PRIVATE_IP_RANGE_FOR_NODES}.${x} >> data.yml
done
j2 cluster.yml.j2 data.yml -o /opt/rancher-setup/cluster.yml

SCRIPT

$kubectl_installation = <<SCRIPT

curl -LOsS https://storage.googleapis.com/kubernetes-release/release/$1/bin/linux/amd64/kubectl
chmod +x kubectl
mv kubectl /usr/local/bin/kubectl
yum install bash-completion -y
echo 'source /usr/share/bash-completion/bash_completion' >> /home/vagrant/.bashrc
echo 'source <(kubectl completion bash)' >> /home/vagrant/.bashrc
echo 'alias k=kubectl' >> /home/vagrant/.bashrc
echo 'complete -F __start_kubectl k' >> /home/vagrant/.bashrc

SCRIPT

Vagrant.configure("2") do |config|
    #Common setup
    config.vm.box = "#{VM_IMAGE}"
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provision "prepare_basic_settings", type: "shell", inline: $prepare_basic_settings, privileged: false
    # Control node
    config.vm.define "ctl-node" do |ctl_node|
        ctl_node.vm.network :private_network, ip: "#{CONTROL_NODE_IP}"
        ctl_node.vm.hostname = "ctl-node"
        ctl_node.vm.provider :"#{PROVIDER}" do |box|
            box.cpus = CPU_CORES_CTL
            box.memory = MEMORY_CTL
        end
        ctl_node.vm.provision "terraform_installation", type: "shell", inline: $terraform_installation, privileged: true
        ctl_node.vm.provision "rke_cluster_yaml_generation", type: "shell", inline: $rke_cluster_yaml_generation, privileged: false
        ctl_node.vm.provision "kubectl_installation", type: "shell", inline: $kubectl_installation, args: [KUBECTL_VERSION], privileged: true
    end
    # Setup Rancher nodes
    (0..RANCHER_NODES-1).each do |i|
        config.vm.define "rancher-node-#{i}" do |rancher_node|
            rancher_node.vm.network :private_network, ip: "#{RANCHER_NODES_BASE_IP}#{i}"
            rancher_node.vm.hostname = "rancher-node-#{i}"
            rancher_node.vm.provider :"#{PROVIDER}" do |box|
                box.cpus = CPU_CORES_RANCHER_NODES
                box.memory = MEMORY_RANCHER_NODES
            end
        end
    end
    # Setup K8s nodes
    (0..K8S_NODES-1).each do |i|
        config.vm.define "k8s-node-#{i}" do |k8s_node|
            k8s_node.vm.network :private_network, ip: "#{K8S_NODES_BASE_IP}#{i}"
            k8s_node.vm.hostname = "k8s-node-#{i}"
            k8s_node.vm.provider :"#{PROVIDER}" do |box|
                box.cpus = CPU_CORES_K8S_NODES
                box.memory = MEMORY_K8S_NODES
            end
        end
    end
end